/* Receitas da Clica e Cozinha.
   Método tradicional, escrito para se seguir em casa (pesos, tempos, ponto).
   Ainda não foram cozinhadas nesta cozinha da app — o aviso na ficha é de propósito. */
const RECIPES = {
  muqueca: {
    time: 75, prep: 35, cook: 40, serves: 4, difficulty: "media",
    pt: {
      name: "Muqueca capixaba",
      origin: "Vitória, Espírito Santo. Comida típica do estado (Lei 7.567/2003). Dia da Moqueca em Vitória: 30 de setembro. A panela de barro das paneleiras de Goiabeiras é o recipiente certo.",
      honest: "O lume é na sua casa. Esta ficha segue o método capixaba (urucum, sem dendê, sem coco, sem água). Não digo que já a fiz nesta panela. Confirme cada ponto. Peixe duvidoso: não faça.",
      mise: [
        "Cheire o peixe: mar, nunca amoníaco. Postas de 2,5–3 cm, ~300 g cada (4 postas = 1,2 kg).",
        "Corte tomate e cebola em rodelas da mesma espessura (~5 mm), para cozerem iguais.",
        "Pique coentro e cebolinha. Separe 1/4 para o fim.",
        "Faça a tinta de urucum e deixe à mão. Tempere o peixe e conte 30 min.",
        "Se a panela é de barro: lume baixo 5 min com um fio de azeite, vazia. Barro frio em fogo alto racha.",
      ],
      equipment: ["Panela de barro com tampa (ou ferro/antiaderente pesada — adaptação, não tradição)", "Pano grosso nas asas", "Panela pequena para o pirão"],
      ings: [
        ["1,2 kg", "peixe branco firme em 4 postas de 2,5–3 cm (badejo, robalo, namorado, cação)"],
        ["1", "cabeça e espinhas do mesmo peixe, para o pirão"],
        ["2", "limões (80 ml de sumo no total: 50 ml no peixe, 30 ml no fim)"],
        ["12 g", "sal fino só no peixe (1% do peso)"],
        ["400 g", "tomate maduro em rodelas de 5 mm"],
        ["300 g", "cebola branca em rodelas de 5 mm"],
        ["20 g", "alho picado (4 dentes)"],
        ["40 g", "coentro fresco picado"],
        ["30 g", "cebolinha verde picada"],
        ["50 ml", "azeite"],
        ["30 ml", "tinta de urucum (ver passo) ou 8 g de colorau seco dissolvido no azeite"],
        ["400 ml", "água, só para o pirão da cabeça — nunca na muqueca"],
        ["80 g", "farinha de mandioca, para o pirão"],
        ["a gosto", "pimenta-do-reino; 1 malagueta se quiser arder"],
      ],
      steps: [
        { do: "Peixe: 12 g de sal + 50 ml de sumo de limão. 30 min no fresco, destapado. Reserve cabeça e espinhas na frigideira com 400 ml de água para o pirão, lume baixo, enquanto espera.", cue: "O peixe cheira a mar e limão. Se cheirar a amoníaco ou estiver mole, deite fora — não “aproveite”." },
        { do: "Tinta de urucum: 40 ml de óleo de milho + 1 c. sopa rasa de sementes, lume baixo 2 min. Coe. Fica laranja-vermelho e cheira a terra doce, não a queimado. Colorau seco: 8 g + 30 ml do azeite, fora do lume.", cue: "Cor de páprica. Se o óleo escurecer a café, deite fora e refaça." },
        { do: "Panela de barro já quente no baixo. 30 ml de azeite, alho 30 s, metade da cebola, tomate, coentro e cebolinha. 2 min. Não deixe o alho passar de loiro.", cue: "Cebola translúcida, alho a cheirar, nada preto no fundo." },
        { do: "Postas numa só camada. Cubra com o resto dos vegetais e ervas. Tinta de urucum + 20 ml de azeite. Tampe. Zero água. Zero virar com colher.", cue: "Tudo vermelho-verde por cima. O fundo não deve chapinhar como um ensopado." },
        { do: "Lume médio até ouvir a primeira fervura (4–6 min). Baixe a mínimo. 18 min se as postas tiverem 2,5 cm; 22 min se tiverem 3 cm. De 3 em 3 min, agite a panela com o pano.", cue: "Ponto do peixe: o centro ficou opaco e o garfo entra sem luta. O molho é pouco, vermelho, brilhante. Se nada um bocado, alguém deitou água — da próxima, não." },
        { do: "30 ml de limão no fim, o 1/4 das ervas, pimenta. Prove o sal (o peixe já levou 12 g; só acrescente se o tomate estiver doce demais).", cue: "Ácido no fim, não no início a mais — limão a mais no cru endurece a superfície." },
        { do: "Pirão, à parte: a água da cabeça já cozeu 30 min. Coe. Lume médio, chuva de 80 g de farinha de mandioca a mexer até fita na colher (3–4 min). Sal se faltar.", cue: "Pirão cai em fita, não em sopa nem em bola. Se empelotar, passe a peneira e volte 1 min." },
      ],
      tip: "Sem barro: ferro ou antiaderente pesada com tampa. Diga à mesa que a panela não é a de Goiabeiras. O método (sem água, sem virar) mantém-se.",
      mistakes: "Água na muqueca. Virar as postas. Dendê ou coco. Barro no fogo alto a vazio. Limão a mais nos 30 min (o peixe “cozinha” por fora e seca).",
      serve: "Na panela, ao centro. Arroz branco solto (400 g cru para 4). Pirão à parte. Prato fundo.",
    },
    es: {
      name: "Muqueca capixaba",
      origin: "Vitória, Espírito Santo. Comida típica del estado. 30 de septiembre en Vitória. La olla de barro de Goiabeiras es el recipiente correcto.",
      honest: "El fuego es en su casa. Método capixaba: urucum, sin dendê, sin coco, sin agua. No digo que la haya hecho en esta olla. Confirme cada punto.",
      mise: [
        "Huela el pescado: mar, nunca amoníaco. Rodajas de 2,5–3 cm, ~300 g (4 = 1,2 kg).",
        "Tomate y cebolla en rodajas de 5 mm.",
        "Pique cilantro y cebollino; separe 1/4 para el final.",
        "Tinta de urucum a mano. Pescado 30 min con sal y lima.",
        "Olla de barro: fuego bajo 5 min con un hilo de aceite. Barro frío a fuego alto se racha.",
      ],
      equipment: ["Olla de barro con tapa (o hierro — adaptación)", "Paño grueso", "Olla pequeña para el pirão"],
      ings: [
        ["1,2 kg", "pescado blanco firme en 4 rodajas de 2,5–3 cm"],
        ["1", "cabeza y espinas, para el pirão"],
        ["2", "limones (80 ml de zumo: 50 ml al pescado, 30 ml al final)"],
        ["12 g", "sal fina solo en el pescado (1%)"],
        ["400 g", "tomate en rodajas de 5 mm"],
        ["300 g", "cebolla blanca en rodajas de 5 mm"],
        ["20 g", "ajo picado"],
        ["40 g", "cilantro"],
        ["30 g", "cebollino"],
        ["50 ml", "aceite de oliva"],
        ["30 ml", "tinta de urucum o 8 g de colorau en el aceite"],
        ["400 ml", "agua solo para el pirão"],
        ["80 g", "harina de yuca para el pirão"],
      ],
      steps: [
        { do: "Pescado: 12 g de sal + 50 ml de lima, 30 min en frío. Cabeza con 400 ml de agua a fuego bajo para el pirão.", cue: "Huele a mar. Si huele a amoníaco, tírelo." },
        { do: "Urucum: 40 ml de aceite de maíz + 1 cda. de semillas, 2 min bajo. Cuele. Colorau: 8 g + 30 ml de aceite, fuera del fuego.", cue: "Naranja de pimentón, no café." },
        { do: "Olla ya caliente. 30 ml de aceite, ajo 30 s, mitad de verdura 2 min.", cue: "Cebolla translúcida, ajo rubio." },
        { do: "Pescado en una capa. Resto de verdura. Urucum y 20 ml de aceite. Tape. Sin agua. Sin voltear.", cue: "Rojo-verde encima. No debe chapotear como un guiso." },
        { do: "Hasta el primer hervor (4–6 min). Mínimo. 18 min si 2,5 cm; 22 min si 3 cm. Agite con el paño cada 3 min.", cue: "Centro opaco, tenedor fácil. Poca salsa roja. Si nada, alguien echó agua." },
        { do: "30 ml de lima al final, 1/4 de hierbas. Pruebe la sal.", cue: "El ácido va al final. Lima de más al inicio reseca." },
        { do: "Pirão: cuele el caldo de la cabeza. 80 g de harina de yuca en lluvia hasta cinta (3–4 min).", cue: "Cae en cinta, no sopa ni bola." },
      ],
      tip: "Sin barro: hierro o antiadherente pesada. Dígalo en la mesa. El método se mantiene.",
      mistakes: "Agua en la muqueca. Voltear. Dendê o coco. Barro vacío a fuego alto.",
      serve: "En la olla. Arroz blanco (400 g crudo para 4). Pirão aparte.",
    },
  },
  "casquinha-siri": {
    time: 45, prep: 20, cook: 25, serves: 4, difficulty: "facil",
    pt: {
      name: "Casquinha de siri",
      origin: "Vila Velha e o litoral capixaba (Praia da Costa, Itapoã). Petisco de bar de praia à moda do Estado.",
      honest: "O lume é na sua casa. Moda capixaba: siri sequinho, azeite, coentro — sem coco e sem dendê. Carne já catada (congelada serve). 100 g de recheio por casca.",
      mise: [
        "Descongele o siri no frigorífico, nunca no micro-ondas. Aperte num pano até parar de pingar.",
        "Prove um fio: se ranger (areia), água fria, escorra, seque outra vez.",
        "Pique cebola, alho, tomate e coentro. Lave as 4 cascas com escova e seque, ou use 4 ramequins de 8–9 cm.",
        "Forno a 200 °C, calor em cima e baixo, grelha ao meio. Se for ventilado, 185 °C.",
      ],
      equipment: ["Frigideira", "Pano limpo", "4 cascas ou ramequins de forno"],
      ings: [
        ["400 g", "carne de siri limpa e desfiada, bem escorrida (peso já seco)"],
        ["80 g", "cebola em cubos de 3 mm"],
        ["10 g", "alho picado (2 dentes)"],
        ["80 g", "tomate sem sementes, cubos de 5 mm"],
        ["20 g", "coentro fresco picado"],
        ["40 ml", "azeite"],
        ["20 g", "manteiga"],
        ["30 g", "farinha de mandioca para gratinar (panko só se não houver mandioca — adaptação)"],
        ["8 g", "sal"],
        ["15 ml", "sumo de limão (½ limão) + 1 limão em gomos"],
        ["a gosto", "pimenta-do-reino"],
      ],
      steps: [
        { do: "Azeite + 10 g de manteiga, lume médio. Cebola 4 min até translúcida, sem cor. Alho 30 s. Tomate 3 min até amolecer e soltar um pouco de suco.", cue: "Fundo húmido de tomate, sem tostar. Se o alho escurecer, deite fora este fundo e recomece — amarga o siri." },
        { do: "Siri, 8 g de sal, pimenta. Lume médio-alto 6–8 min, mexendo. O suco tem de evaporar. 15 ml de limão e o coentro fora do lume forte.", cue: "Ponto: 100 g do recheio aguentam-se na colher e não deitam caldo no prato. Se papo, +2 min. Se seco como farofa, 1 c. sopa de água e 30 s." },
        { do: "4 montes de 100 g. Farinha em camada fina. 10 g de manteiga em pontos. Forno 10 min no meio; se não dourar, 2 min em cima.", cue: "Beiras cor de palha, centro húmido. Se a farinha estiver branca aos 10 min, mais 2. Se estiver castanha-escura, já passou." },
        { do: "Sirva nos 2 min seguintes, gomos de limão à parte. Não tape: a farinha amolece.", cue: "Cheira a mar e manteiga. A casca (ou o ramequim) queima — avise à mesa." },
      ],
      tip: "Sem casca de siri: ramequim. Diga que não é a concha. Sem forno: farinha torrada à parte na manteiga 2 min e polvilhe — fica mais de praia, menos gratinado.",
      mistakes: "Siri a pingar. Coco ou dendê nesta ficha. 80 g de farinha (bolo). Forno 20 min (estopa).",
      serve: "1 casquinha por pessoa como entrada, antes da muqueca. Não é prato único.",
    },
    es: {
      name: "Casquinha de siri (cangrejo)",
      origin: "Vila Velha y el litoral capixaba.",
      honest: "El fuego es en su casa. Moda capixaba: cangrejo seco, aceite, cilantro. Sin coco ni dendê. 100 g por casca.",
      mise: [
        "Descongele en nevera. Exprima en un paño.",
        "Si cruje (arena), enjuague y seque.",
        "Pique verdura. 4 conchas o ramequines de 8–9 cm.",
        "Horno 200 °C (ventilado 185 °C), rejilla al medio.",
      ],
      equipment: ["Sartén", "Paño", "4 conchas o ramequines"],
      ings: [
        ["400 g", "carne de cangrejo limpia, bien escurrida"],
        ["80 g", "cebolla en cubos de 3 mm"],
        ["10 g", "ajo picado"],
        ["80 g", "tomate sin semillas"],
        ["20 g", "cilantro"],
        ["40 ml", "aceite de oliva"],
        ["20 g", "mantequilla"],
        ["30 g", "harina de yuca para gratinar"],
        ["8 g", "sal"],
        ["15 ml", "zumo de limón + limón en gajos"],
      ],
      steps: [
        { do: "Aceite + 10 g de mantequilla. Cebolla 4 min. Ajo 30 s. Tomate 3 min.", cue: "Fondo húmedo, ajo rubio. Si se quema, empiece de nuevo." },
        { do: "Cangrejo, 8 g de sal. 6–8 min medio-alto. Lima y cilantro fuera del fuego fuerte.", cue: "100 g se aguantan en la cuchara, sin caldo." },
        { do: "4 montones de 100 g. Harina fina. 10 g de mantequilla. 10 min; +2 si no dora.", cue: "Bordes paja, centro húmedo." },
        { do: "En 2 min, limón aparte. No tape.", cue: "La concha quema: avise." },
      ],
      tip: "Sin concha: ramequin. Sin horno: harina tostada 2 min en mantequilla.",
      mistakes: "Cangrejo goteando. Coco o dendê. Demasiada harina. 20 min de horno.",
      serve: "Entrante. Una por persona, antes de la muqueca.",
    },
  },
  feijoada: {
    time: 210, prep: 20, cook: 190, serves: 6, difficulty: "media",
    pt: {
      name: "Feijoada",
      origin: "Rio de Janeiro — o prato de sábado. Feijão preto e carne de porco em lume brando.",
      honest: "Versão caseira para 6, com cortes que se encontram no talho. Não leva orelha nem pé; se os quiser, some 200 g e coza-os com o feijão desde o início.",
      equipment: ["Panela grande (5 l)", "Frigideira para o refogado"],
      ings: [
        ["500 g", "feijão preto seco"],
        ["300 g", "entrecosto ou costela de porco"],
        ["200 g", "linguiça calabresa em rodelas"],
        ["150 g", "bacon em cubos"],
        ["150 g", "lombo ou paio, em cubos"],
        ["2", "folhas de louro"],
        ["1", "cebola média (~150 g), picada"],
        ["4 dentes", "alho picado"],
        ["8 g", "sal, só no fim"],
        ["a gosto", "pimenta-do-reino"],
        ["para servir", "arroz, couve fatiada, laranja em gomos, farofa"],
      ],
      steps: [
        { do: "De véspera: lave o feijão. Cubra com água a dobrar. Molho 10–12 h. Escorra. A água do molho deita-se fora.", cue: "O grão inchou e a pele está lisa." },
        { do: "Na panela: feijão, costela, paio, louro e água a cobrir 4 cm. Ferva, baixe o lume, tampa entreaberta 1 h 15. Espume a espuma cinzenta.", cue: "O feijão começa a abrir. A costela ainda está firme." },
        { do: "Frigideira: bacon até soltar gordura; linguiça 3 min; cebola 4 min; alho 30 s. Deite este refogado na panela. Coza mais 40–50 min.", cue: "O caldo engrossa e cobre o dorso da colher. O feijão amassa entre dois dedos." },
        { do: "Sal só agora (8 g, prove). Pimenta. Se estiver ralo, amasse 2 colheres de feijão contra a parede da panela.", cue: "O caldo é escuro e ligado, não água preta." },
        { do: "Descanse 15 min tampado. Sirva com arroz, couve passada 1 min em alho, laranja e farofa.", cue: "A laranja corta a gordura. Se o caldo gelar em bloco no prato, está no ponto — aqueça de novo em lume baixo com um fio de água." },
      ],
      tip: "Melhor no dia seguinte. Guarde até 3 dias no frio. Reaqueça só a parte que vai comer.",
      mistakes: "Sal no início (o feijão endurece). Molho de véspera deitado na panela (escurece e azeda). Lume forte 3 h (grão esfarela, caldo queima).",
      serve: "Prato fundo. 1 concha de feijoada + arroz. Couve e laranja no mesmo prato.",
    },
    es: {
      name: "Feijoada",
      origin: "Río de Janeiro — el plato del sábado. Alubia negra y cerdo a fuego lento.",
      honest: "Versión casera para 6. Sin oreja ni pie; si los quiere, sume 200 g desde el inicio.",
      equipment: ["Olla grande (5 l)", "Sartén"],
      ings: [
        ["500 g", "alubias negras secas"],
        ["300 g", "costilla de cerdo"],
        ["200 g", "chorizo o longaniza en rodajas"],
        ["150 g", "beicon en cubos"],
        ["150 g", "lomo de cerdo en cubos"],
        ["2", "hojas de laurel"],
        ["1", "cebolla (~150 g)"],
        ["4 dientes", "ajo"],
        ["8 g", "sal, solo al final"],
        ["al gusto", "pimienta"],
        ["para servir", "arroz, berza, naranja, farofa"],
      ],
      steps: [
        { do: "Víspera: lave y cubra de agua (el doble). 10–12 h. Escurra. Tire el agua del remojo.", cue: "El grano hinchó." },
        { do: "Alubias, costilla, lomo, laurel y agua 4 cm por encima. Herva, baje, 1 h 15. Espume.", cue: "El grano empieza a abrirse." },
        { do: "Beicon, chorizo, cebolla, ajo. Al caldo. 40–50 min más.", cue: "El caldo cubre el dorso de la cuchara. El grano se aplasta entre dos dedos." },
        { do: "Sal ahora. Si está ralo, machaque 2 cucharas de alubia contra la olla.", cue: "Caldo oscuro y ligado." },
        { do: "15 min tapado. Arroz, berza 1 min con ajo, naranja y farofa.", cue: "La naranja corta la grasa." },
      ],
      tip: "Mejor al día siguiente. 3 días en nevera. Recaliente solo lo que vaya a comer.",
      mistakes: "Sal al inicio. Usar el agua del remojo. Fuego fuerte 3 h.",
      serve: "Plato hondo. Un cucharón + arroz.",
    },
  },
  acaraje: {
    time: 90, prep: 40, cook: 50, serves: 8, difficulty: "dificil",
    pt: {
      name: "Acarajé",
      origin: "Bahia. Bolinho de feijão-frade frito em dendê, recheado. Ofício das baianas é património.",
      honest: "O difícil é pelar o feijão e a temperatura do dendê. O vatapá vai aqui em versão curta, para o prato ficar completo na app — não é o vatapá de festa, é o suficiente para rechear 8 bolos.",
      equipment: ["Liquidificadora ou triturador", "Panela funda para fritar", "Termómetro de açúcar se tiver (180 °C)"],
      ings: [
        ["400 g", "feijão-frade seco (black-eyed pea)"],
        ["150 g", "cebola (massa) + 80 g (vatapá)"],
        ["8 g", "sal"],
        ["500 ml", "azeite de dendê para fritar (reutilize; não deite fora a quente)"],
        ["80 g", "camarão seco, sem casca, para o vatapá e o recheio"],
        ["60 g", "pão do dia anterior, molhado e espremido"],
        ["100 ml", "leite de coco (só no vatapá)"],
        ["30 ml", "dendê para o vatapá"],
        ["2", "tomates para a salada"],
        ["a gosto", "pimenta e coentros na salada"],
      ],
      steps: [
        { do: "Feijão de molho 12 h. Esfregue entre as mãos dentro de água: a pele sobe. Deite a pele fora. Repita até o grão ficar amarelo-claro. Escorra muito bem e seque num pano 15 min.", cue: "Quase sem peles pretas. Se estiver molhado, o bolo bebe óleo." },
        { do: "Triture o feijão com 150 g de cebola até massa lisa e aerada, 2–3 min. Sal (8 g). A massa deve cair da colher em fita, não em bloco.", cue: "Se estiver rija, 1 c. sopa de água. Se estiver sopa, mais 10 min no pano." },
        { do: "Vatapá rápido: refogue 80 g de cebola, 40 g de camarão seco triturado, pão, 100 ml de coco e 30 ml de dendê, 8 min, até pasta. Reserve. Salada: tomate em cubos, o resto do camarão, pimenta.", cue: "O vatapá não escorre do prato; a salada está crua e ácida." },
        { do: "Aqueça o dendê a 175–180 °C (um cubo de massa sobe e doura em 60–90 s, sem queimar). Com duas colheres, faça bolos ovais (~80 g). Frite 3–4 min até dourado-escuro. Escorra em papel.", cue: "Casca crocante, miolo húmido. Se o óleo fumegar, baixe o lume." },
        { do: "Abra ao meio (não até o fim). Vatapá, camarão, salada. Sirva quente.", cue: "O bolo aguenta na mão sem desfazer. Se esfarelar, a massa estava seca demais." },
      ],
      tip: "Dendê a menos de 170 °C ensopa o bolo; a mais de 190 °C queima por fora e cru por dentro.",
      mistakes: "Não pelar o feijão (massa preta e amarga). Massa molhada. Óleo frio. Rechear com vatapá de supermercado muito doce sem provar.",
      serve: "1 acarajé por pessoa como lanche. Prato de papel ou prato raso.",
    },
    es: {
      name: "Acarajé",
      origin: "Bahía. Buñuelo de frijol de careta frito en dendê.",
      honest: "Lo difícil es pelar el frijol y el punto del aceite. El vatapá va en versión corta para poder rellenar en casa.",
      equipment: ["Trituradora", "Olla honda", "Termómetro si tiene (180 °C)"],
      ings: [
        ["400 g", "frijol de careta seco"],
        ["150 g", "cebolla (masa) + 80 g (vatapá)"],
        ["8 g", "sal"],
        ["500 ml", "aceite de palma (dendê) para freír"],
        ["80 g", "camarón seco"],
        ["60 g", "pan del día anterior, remojado"],
        ["100 ml", "leche de coco (solo vatapá)"],
        ["30 ml", "dendê para el vatapá"],
        ["2", "tomates para la ensalada"],
      ],
      steps: [
        { do: "Remojo 12 h. Frote en agua: la piel sube. Escurra y seque 15 min en un paño.", cue: "Grano amarillo, casi sin piel. Si está mojado, bebe aceite." },
        { do: "Triture con 150 g de cebolla hasta masa aireada. 8 g de sal. Debe caer en cinta.", cue: "Si está dura, 1 cda. de agua." },
        { do: "Vatapá: cebolla, camarón triturado, pan, coco y dendê, 8 min. Ensalada de tomate.", cue: "El vatapá no chorrea." },
        { do: "Dendê a 175–180 °C. Bolitas de ~80 g. 3–4 min. Escurra.", cue: "Corteza crujiente, interior húmedo." },
        { do: "Abra, rellene, sirva caliente.", cue: "Aguanta en la mano. Si se desmigaja, la masa estaba seca." },
      ],
      tip: "Menos de 170 °C ensopa; más de 190 °C quema fuera y crudo dentro.",
      mistakes: "No pelar. Masa mojada. Aceite frío.",
      serve: "1 acarajé por persona.",
    },
  },
  "pao-queijo": {
    time: 50, prep: 20, cook: 30, serves: 20, difficulty: "facil",
    pt: {
      name: "Pão de queijo",
      origin: "Minas Gerais. Polvilho de mandioca e queijo. O miolo oco vem do polvilho azedo.",
      honest: "Medidas em gramas. Polvilho azedo é o certo para o oco; se só tiver doce, o pão fica mais denso — ainda come-se.",
      equipment: ["Tigela grande", "Tabuleiro com papel", "Forno"],
      ings: [
        ["250 g", "polvilho azedo"],
        ["250 g", "polvilho doce (ou 500 g só azedo, se não houver doce)"],
        ["250 ml", "leite gordo"],
        ["80 ml", "óleo"],
        ["50 g", "manteiga"],
        ["10 g", "sal"],
        ["2", "ovos M (~110 g sem casca)"],
        ["200 g", "queijo minas padrão ralado (ou 150 g parmesão + 50 g muçarela)"],
      ],
      steps: [
        { do: "Forno a 180 °C, calor em cima e baixo, tabuleiro no terço inferior. Misture os dois polvilhos e o sal na tigela.", cue: "Farinha solta, sem grumos." },
        { do: "Ferva leite, óleo e manteiga. Quando levantar fervura, deite de uma vez sobre o polvilho. Mexa com colher de pau 1 min: a massa fica empelotada e quente. Espere 8 min, até poder tocar.", cue: "A massa está quente, não queima o dedo. Se ainda fumegar, espere." },
        { do: "1 ovo, misture até sumir. 2.º ovo, misture. Queijo. A massa fica pegajosa e brilhante, descola um pouco da tigela.", cue: "Se esfarelar, 1 colher de leite. Se escorrer, 1 colher de polvilho." },
        { do: "Mãos oleadas. Bolas de 30 g (nozes). Folga de 3 cm no tabuleiro. Asse 22–28 min, até dourar com pintas e crescer.", cue: "Ponto: casca baça-dourada, oco se partir um. Se achatar, a massa estava quente demais quando entrou o ovo." },
        { do: "5 min fora do forno antes de comer. Recolhe. Congela cru: asse congelado + 5 min.", cue: "Quente, o miolo puxa fio de queijo." },
      ],
      tip: "Não abra o forno nos primeiros 15 min. O oco cai se o choque de frio chegar cedo.",
      mistakes: "Ovos na massa a ferver (cozinham e o pão não cresce). Só polvilho doce (fica biscoito). Bolas de 80 g (crus por dentro).",
      serve: "Café. 3–4 unidades por pessoa.",
    },
    es: {
      name: "Pão de queijo",
      origin: "Minas Gerais. Almidón de yuca y queso. El hueco sale del polvilho agrio.",
      honest: "Pesos en gramos. Sin polvilho agrio el pan queda más denso.",
      equipment: ["Bol", "Bandeja", "Horno"],
      ings: [
        ["250 g", "polvilho agrio (almidón de yuca agrio)"],
        ["250 g", "polvilho dulce"],
        ["250 ml", "leche entera"],
        ["80 ml", "aceite"],
        ["50 g", "mantequilla"],
        ["10 g", "sal"],
        ["2", "huevos M"],
        ["200 g", "queso semiduro rallado"],
      ],
      steps: [
        { do: "Horno 180 °C. Mezcle almidones y sal.", cue: "Sin grumos." },
        { do: "Hierva leche, aceite y mantequilla. Vierta de golpe. Espere 8 min.", cue: "Masa caliente, no quema el dedo." },
        { do: "Huevos uno a uno. Queso. Masa pegajosa y brillante.", cue: "Si se desmigaja, 1 cda. de leche." },
        { do: "Bolas de 30 g. 22–28 min, hasta dorar y crecer.", cue: "Corteza mate-dorada; al partir, hueco." },
        { do: "5 min fuera. Se puede congelar crudo.", cue: "El queso hila en caliente." },
      ],
      tip: "No abra el horno 15 min.",
      mistakes: "Huevos en masa hirviendo. Solo almidón dulce. Bolas de 80 g.",
      serve: "Café. 3–4 por persona.",
    },
  },
  virado: {
    time: 55, prep: 20, cook: 35, serves: 4, difficulty: "media",
    pt: {
      name: "Virado à paulista",
      origin: "São Paulo. Feijão-tutu na gordura da linguiça, com ovo, banana, couve e torresmo.",
      honest: "O feijão já vai cozido (400 g de mulatinho ou carioca, escorrido). O 'virado' é o refogado até secar e pegar a gordura — não é uma feijoada.",
      equipment: ["Frigideira larga", "Panela para a couve"],
      ings: [
        ["400 g", "feijão-mulatinho ou carioca, cozido e escorrido (sem muito caldo)"],
        ["250 g", "linguiça toscana ou calabresa"],
        ["80 g", "torresmo ou bacon em cubos"],
        ["4", "ovos"],
        ["2", "bananas-da-terra maduras, em gomos"],
        ["200 g", "couve-manteiga em tiras finas"],
        ["2 dentes", "alho"],
        ["6 g", "sal no total"],
        ["400 g", "arroz branco cozido, para montar"],
      ],
      steps: [
        { do: "Torresmo/bacon em frigideira seca, lume médio, 6 min até dourar. Reserve. Na gordura, linguiça 8 min até dourar. Reserve.", cue: "A linguiça está cozida (sem rosa no corte) e há 2–3 c. sopa de gordura na panela." },
        { do: "No mesmo fundo: feijão 5–7 min, amassando metade com a colher, até secar e ficar um tutu brilhante. Sal (3 g).", cue: "O feijão puxa para o centro e não deita caldo no prato." },
        { do: "Outra frigideira: banana 2 min por lado até dourar. Ovos estrelados, gema ainda mole (2 min). Couve com alho 1 min — tem de ficar verde, não parda.", cue: "Couve brilhante. Gema treme." },
        { do: "Monte: arroz, tutu, linguiça, ovo, banana, couve, torresmo.", cue: "Um prato, tudo ao lado. Come-se misturando." },
      ],
      tip: "Banana demasiado verde amarga; demasiado preta desfaz. Casca amarela com pintas.",
      mistakes: "Feijão com muito caldo (vira sopa). Couve 10 min (fica cinzenta). Ovo duro.",
      serve: "1 prato por pessoa. É almoço, não entrada.",
    },
    es: {
      name: "Virado paulista",
      origin: "São Paulo. Frijol sofrito en la grasa del chorizo, con huevo, plátano y berza.",
      honest: "El frijol ya va cocido. No es una feijoada: se seca en la sartén.",
      equipment: ["Sartén ancha", "Olla para la berza"],
      ings: [
        ["400 g", "frijol cocido y escurrido"],
        ["250 g", "longaniza o chorizo"],
        ["80 g", "torreznos o beicon"],
        ["4", "huevos"],
        ["2", "plátanos macho maduros"],
        ["200 g", "berza en tiras"],
        ["2 dientes", "ajo"],
        ["6 g", "sal"],
        ["400 g", "arroz blanco"],
      ],
      steps: [
        { do: "Torreznos 6 min. Longaniza 8 min. Reserve.", cue: "La longaniza no queda rosa; hay grasa en la sartén." },
        { do: "Frijol 5–7 min, machacando la mitad, hasta secar. 3 g de sal.", cue: "No suelta caldo en el plato." },
        { do: "Plátano 2 min por lado. Huevos 2 min, yema blanda. Berza con ajo 1 min.", cue: "Berza verde. Yema que tiembla." },
        { do: "Monte todo en el plato.", cue: "Se come mezclando." },
      ],
      tip: "Plátano con pintas, no verde.",
      mistakes: "Frijol caldoso. Berza 10 min. Huevo duro.",
      serve: "Un plato por persona.",
    },
  },
  tacaca: {
    time: 50, prep: 20, cook: 30, serves: 4, difficulty: "media",
    pt: {
      name: "Tacacá",
      origin: "Pará e Amazónia. Tucupi, jambu e goma de mandioca na cuia. O jambu formiga a boca — é o ponto, não um defeito.",
      honest: "Tucupi e jambu vendem-se em lojas brasileiras ou congelados. Sem tucupi não há tacacá; não substitua por caldo de galinha. Goma = fécula de mandioca hidratada, não tapioca em pérola.",
      equipment: ["Panela", "4 cuias ou tigelas fundas"],
      ings: [
        ["1 l", "tucupi (filtrado)"],
        ["1 maço", "jambu (ou 80 g de folhas)"],
        ["80 g", "goma de mandioca (fécula)"],
        ["200 ml", "água fria para a goma"],
        ["120 g", "camarão seco médio"],
        ["3 dentes", "alho"],
        ["6 g", "sal"],
        ["a gosto", "pimenta-de-cheiro"],
      ],
      steps: [
        { do: "Tucupi em lume médio com alho amassado 15 min, sem fervura forte. O cheiro cru (ácido) tem de sair. Sal (6 g).", cue: "Cheira a mandioca cozida, não a seiva crua." },
        { do: "Goma: 80 g + 200 ml de água fria, mexer até leite branco. Reserve 10 min. Fica um leite, não um cola.", cue: "Sem grumos. Se estiver cola, mais 2 c. sopa de água." },
        { do: "Jambu: água a ferver, 1 min. Escorra. Não ferva 10 min — amarga e perde o formigar.", cue: "Folhas verdes, cabos tenros." },
        { do: "Camarão: hidrate 10 min em água quente se estiver muito seco. Escorra.", cue: "Flexível, não pedra." },
        { do: "Na cuia: 3 c. sopa de goma. Deite tucupi bem quente por cima (a goma coalha). Jambu, camarão, pimenta. Sirva de imediato.", cue: "Há um fundo branco elástico e um caldo amarelo. A boca formiga aos 30 s — é o jambu." },
      ],
      tip: "Depois de juntar o jambu ao tucupi, não ferva: amarga. O quente vem do caldo, não de mais lume.",
      mistakes: "Ferver o tucupi com o jambu. Goma de pérolas de tapioca. Caldo de galinha no lugar do tucupi.",
      serve: "1 cuia por pessoa. Colher. É entrada ou lanche da tarde.",
    },
    es: {
      name: "Tacacá",
      origin: "Pará y Amazonia. Tucupi, jambu y goma de yuca. El jambu hormiguea en la boca: es el punto.",
      honest: "Sin tucupi no hay tacacá. No lo sustituya por caldo de pollo.",
      equipment: ["Olla", "4 cuencos hondos"],
      ings: [
        ["1 l", "tucupi filtrado"],
        ["1 manojo", "jambu (~80 g)"],
        ["80 g", "fécula de yuca"],
        ["200 ml", "agua fría"],
        ["120 g", "camarón seco"],
        ["3 dientes", "ajo"],
        ["6 g", "sal"],
        ["al gusto", "ají dulce"],
      ],
      steps: [
        { do: "Tucupi con ajo 15 min a fuego medio, sin hervor fuerte. 6 g de sal.", cue: "Huele a yuca cocida, no a savia cruda." },
        { do: "Goma + agua fría. 10 min. Debe ser leche, no cola.", cue: "Sin grumos." },
        { do: "Jambu 1 min en agua hirviendo. Escurra.", cue: "Hojas verdes." },
        { do: "Camarón: hidrate 10 min si está muy seco.", cue: "Flexible." },
        { do: "En el cuenco: goma, tucupi muy caliente, jambu, camarón. Al momento.", cue: "Fondo blanco elástico y caldo amarillo. La boca hormiguea." },
      ],
      tip: "No hiervan juntos tucupi y jambu.",
      mistakes: "Hervir el jambu en el tucupi. Perlas de tapioca. Caldo de pollo.",
      serve: "Un cuenco por persona.",
    },
  },
  "carne-sol": {
    time: 50, prep: 25, cook: 25, serves: 4, difficulty: "facil",
    pt: {
      name: "Carne de sol com macaxeira",
      origin: "Nordeste. Carne salgada e seca ao sol, dessalgada e grelhada, com aipim.",
      honest: "Se não achar carne de sol, use alcatra salgada 24 h com 3% de sal e seca no frio destapada 12 h — é um atalho, não o produto do sertão.",
      equipment: ["Grelha ou frigideira de ferro", "Panela para a macaxeira"],
      ings: [
        ["500 g", "carne de sol (alcatra ou coxão)"],
        ["800 g", "macaxeira / aipim, descascada"],
        ["40 g", "manteiga de garrafa ou manteiga"],
        ["80 ml", "leite morno"],
        ["1", "cebola em penas"],
        ["a gosto", "pimenta-do-reino"],
      ],
      steps: [
        { do: "Dessalgue: cubra a carne de água fria 45 min, troque a água uma vez. Prove um canto: deve estar salgada, não impossível. Seque com papel.", cue: "A superfície não está branca de sal. Se ainda arder, mais 20 min de água." },
        { do: "Macaxeira em água a ferver com um fio de sal, 20–25 min, até o garfo entrar. Escorra. Amasse com 30 g de manteiga e o leite. Prove o sal.", cue: "Puré grosso, com alguns grumos. Não é papa de bebé." },
        { do: "Frigideira bem quente. Carne 3–4 min por lado, sem furar. Descanse 5 min. Cebola na gordura 2 min.", cue: "Crosta dourada, centro ainda rosado se a peça for alta. Se secar como sola, o lume estava baixo tempo demais." },
        { do: "Fatias contra a fibra sobre o puré. Cebola e o resto da manteiga derretida. Pimenta.", cue: "O suco da carne molha o puré." },
      ],
      tip: "Carne de sol já vem curada: não ponha mais sal na peça, só no puré se faltar.",
      mistakes: "Dessalgar 6 h (fica insossa e seca). Furar com o garfo na frigideira. Puré com 2 dl de leite (sopa).",
      serve: "Prato raso. Carne por cima do aipim.",
    },
    es: {
      name: "Carne de sol con yuca",
      origin: "Nordeste de Brasil. Carne salada y seca, asada, con yuca.",
      honest: "Si no hay carne de sol: solomillo con 3% de sal 24 h y 12 h destapado en nevera. Es un atajo.",
      equipment: ["Sartén de hierro", "Olla para la yuca"],
      ings: [
        ["500 g", "carne de sol"],
        ["800 g", "yuca pelada"],
        ["40 g", "mantequilla"],
        ["80 ml", "leche tibia"],
        ["1", "cebolla en pluma"],
        ["al gusto", "pimienta"],
      ],
      steps: [
        { do: "Desale 45 min, cambie el agua una vez. Seque.", cue: "Salada, no imposible. Si arde, 20 min más." },
        { do: "Yuca 20–25 min. Puré con 30 g de mantequilla y leche.", cue: "Grueso, con grumos." },
        { do: "Sartén fuerte. Carne 3–4 min por lado. 5 min de reposo. Cebolla 2 min.", cue: "Costra dorada." },
        { do: "Lonchas contra la fibra sobre el puré.", cue: "El jugo moja la yuca." },
      ],
      tip: "No salar más la pieza; solo el puré si falta.",
      mistakes: "Desalar 6 h. Pinchar la carne. Demasiada leche.",
      serve: "Carne sobre la yuca.",
    },
  },
  paella: {
    time: 55, prep: 15, cook: 40, serves: 4, difficulty: "media",
    pt: {
      name: "Paella valenciana",
      origin: "Valência. Arroz, frango, coelho, bajoca e garrofó. Não leva marisco — essa é outra paella.",
      honest: "Receita da horta, não da praia. Arroz bomba (ou albufera). Relação caldo:arroz ≈ 2,5:1 em volume. Não se mexe depois de espalhar.",
      equipment: ["Paellera de 38–42 cm (ou frigideira larga de 32 cm para 4)", "Lume que aqueça o fundo todo"],
      ings: [
        ["400 g", "arroz bomba"],
        ["1 l", "caldo de galinha bem quente"],
        ["350 g", "frango em pedaços (coxas)"],
        ["250 g", "coelho em pedaços (se não houver, mais 250 g de frango — diga à mesa que foi adaptação)"],
        ["150 g", "bajoca / judía verde em troços"],
        ["100 g", "garrofó ou feijão-branco cozido"],
        ["150 g", "tomate ralado (sem pele)"],
        ["8 g", "sal"],
        ["0,3 g", "açafrão em hebra (uma pitada) ou ½ c. chá de colorau doce + 1 pitada de açafrão"],
        ["60 ml", "azeite"],
        ["1 ramo", "alecrim (tira-se ao 8.º min do arroz)"],
      ],
      steps: [
        { do: "Paellera em lume médio-alto, azeite. Sal nas carnes. Doure 8–10 min até pele cor de canela. Empurre para as bordas.", cue: "Fundo com fond dourado, não preto." },
        { do: "Bajoca 3 min no centro. Tomate 4 min até o azeite separar. Garrofó. Açafrão 20 s.", cue: "O tomate perdeu água e cheira a doce, não a cru." },
        { do: "Caldo quente + 8 g de sal. Ferva 2 min. Prove o caldo: deve estar um pouco mais salgado do que a sopa, porque o arroz bebe.", cue: "Caldo a ferver em toda a superfície." },
        { do: "Arroz em cruz, depois espalhe com o cabo da colher. Alecrim. Cronómetro 18 min. Não mexa. 10 min lume médio, 8 min baixo.", cue: "Aos 12 min o caldo está ao nível do arroz. No fim, ouve-se um crepitar leve — socarrat." },
        { do: "Se ainda houver poça aos 16 min, suba 1 min o lume. Se secar aos 12, 50 ml de caldo quente na borda. Tire o alecrim. Descanse 5 min tapado com um pano (não tampa de panela a condensar).", cue: "Grão inteiro, húmido por dentro, fundo com crosta tostada. Se estiver sopa, passou caldo; se estiver goma, mexeu." },
      ],
      tip: "Socarrat: o crepitar no fim. Se cheirar a queimado amargo, tire do lume já.",
      mistakes: "Mexer o arroz (risoto). Marisco nesta ficha (não é valenciana). Caldo frio. Tampa de vidro a pingar água.",
      serve: "Na paellera, ao centro da mesa. Colher de pau. Limão à parte — em Valência muita gente não põe.",
    },
    es: {
      name: "Paella valenciana",
      origin: "Valencia. Arroz, pollo, conejo, ferraura y garrofón. Sin marisco.",
      honest: "Receta de la huerta. Arroz bomba. Caldo:arroz ≈ 2,5:1. No se remueve.",
      equipment: ["Paella de 38–42 cm", "Fuego que cubra el fondo"],
      ings: [
        ["400 g", "arroz bomba"],
        ["1 l", "caldo de pollo bien caliente"],
        ["350 g", "pollo en trozos"],
        ["250 g", "conejo (si no hay, más pollo — dígalo en la mesa)"],
        ["150 g", "judía verde"],
        ["100 g", "garrofón o judía blanca cocida"],
        ["150 g", "tomate rallado"],
        ["8 g", "sal"],
        ["0,3 g", "azafrán en hebra"],
        ["60 ml", "aceite de oliva"],
        ["1 ramita", "romero"],
      ],
      steps: [
        { do: "Aceite. Sal en las carnes. 8–10 min hasta canela. A los lados.", cue: "Fond dorado, no negro." },
        { do: "Judía 3 min. Tomate 4 min. Garrofón. Azafrán 20 s.", cue: "El tomate ya no está crudo." },
        { do: "Caldo caliente + 8 g de sal. Pruebe: un poco más salado que una sopa.", cue: "Hierve en toda la superficie." },
        { do: "Arroz, extienda. Romero. 18 min sin remover. 10 medio, 8 bajo.", cue: "Al final, un crepitar leve: socarrat." },
        { do: "Si hay charco a los 16 min, suba el fuego 1 min. Romero fuera. 5 min con un paño.", cue: "Grano entero, fondo tostado. Si es sopa, sobró caldo; si es goma, removió." },
      ],
      tip: "Socarrat: crepitar. Si huele a quemado amargo, fuera.",
      mistakes: "Remover. Poner marisco en esta ficha. Caldo frío.",
      serve: "En la paella, al centro. Limón aparte.",
    },
  },
  gazpacho: {
    time: 80, prep: 20, cook: 0, serves: 4, difficulty: "facil",
    pt: {
      name: "Gazpacho andaluz",
      origin: "Andaluzia. Sopa fria de tomate, pão, azeite e vinagre. Sem nata e sem caldo.",
      honest: "O tempo longo é o frio (1 h). Sem tomate maduro de verão, o gazpacho fica insosso — neste caso, 10 g de concentrado de tomate, não açúcar.",
      equipment: ["Triturador", "Peneira (opcional)", "Jarra no frio"],
      ings: [
        ["1 kg", "tomate maduro (rama ou coração-de-boi), em quartos"],
        ["150 g", "pepino, sem sementes se for amargo"],
        ["100 g", "pimento verde italiano"],
        ["40 g", "pão do dia anterior, miolo"],
        ["1 dente", "alho (se for novo; se for velho, ½)"],
        ["80 ml", "azeite virgem"],
        ["25 ml", "vinagre de xerez ou de vinho branco"],
        ["10 g", "sal"],
        ["80 ml", "água fria, só se o triturador não andar"],
      ],
      steps: [
        { do: "Pão 10 min em 50 ml de água. Esprema. Triture tomate, pepino, pimento, alho, pão, sal, vinagre 1 min. Azeite em fio com o motor a andar 30 s.", cue: "Fica veludo, cor de coral. Se ficar rosa-claro, faltou tomate ou sobrou pão." },
        { do: "Peneire se quiser sem pele. Prove: sal, depois vinagre, por último azeite. Frigorífico 60 min mínimo (melhor 2 h).", cue: "Gelado, não fresco de cave. A 4–6 °C o azeite liga e o vinagre acalma." },
        { do: "Sirva com cubos de pepino, pimento e tomate (30 g no total por prato) e um fio de azeite.", cue: "Não vai gelo no copo: dilui. Se estiver ralo, 20 g de pão triturado e 10 min de frio." },
      ],
      tip: "Alho a mais fica a picar 2 h depois. Comece com 1 dente.",
      mistakes: "Nata ou iogurte. Caldo de legumes. Servir tépido. Açúcar para tapar tomate verde.",
      serve: "Tigela ou copo baixo. 250 ml por pessoa.",
    },
    es: {
      name: "Gazpacho andaluz",
      origin: "Andalucía. Sopa fría de tomate, pan, aceite y vinagre.",
      honest: "El tiempo largo es el frío (1 h). Sin tomate de verano, 10 g de concentrado, no azúcar.",
      equipment: ["Trituradora", "Colador opcional", "Jarra en nevera"],
      ings: [
        ["1 kg", "tomate maduro"],
        ["150 g", "pepino"],
        ["100 g", "pimiento verde"],
        ["40 g", "miga de pan del día anterior"],
        ["1 diente", "ajo"],
        ["80 ml", "aceite de oliva virgen"],
        ["25 ml", "vinagre de Jerez"],
        ["10 g", "sal"],
        ["80 ml", "agua fría solo si hace falta"],
      ],
      steps: [
        { do: "Pan 10 min en agua. Exprima. Triture verdura, pan, sal, vinagre. Aceite en hilo 30 s.", cue: "Terciopelo, color coral." },
        { do: "Cuele si quiere. Pruebe. Nevera 60 min (mejor 2 h).", cue: "Frío de nevera, 4–6 °C." },
        { do: "Cubitos de verdura y un hilo de aceite. Sin hielo en el vaso.", cue: "Si está ralo, 20 g de pan y 10 min más." },
      ],
      tip: "Empiece con 1 diente de ajo.",
      mistakes: "Nata. Caldo. Servir tibio. Azúcar.",
      serve: "250 ml por persona.",
    },
  },
  pulpo: {
    time: 70, prep: 10, cook: 60, serves: 4, difficulty: "facil",
    pt: {
      name: "Polvo à galega",
      origin: "Galiza. Polvo, cachelos, pimentón e azeite. O truque é o congelado e o 'susto' na água.",
      honest: "Polvo já congelado (e descongelado no frio) fica mais tenro. Pimentón doce de la Vera; o picante é opcional por cima.",
      equipment: ["Panela larga", "Tesoura de cozinha", "Fonte rasa"],
      ings: [
        ["1,2 kg", "polvo cru, de preferência já congelado e descongelado 24 h no frio"],
        ["800 g", "batata para cozer, em gomos com pele"],
        ["8 g", "sal grosso"],
        ["8 g", "pimentón doce"],
        ["80 ml", "azeite"],
        ["a gosto", "pimentón picante (pitada)"],
      ],
      steps: [
        { do: "Água a ferver, sem sal ainda. Pegue o polvo pelos tentáculos e mergulhe 3 vezes (3 s cada) — o 'susto', para os tentáculos enroscarem. Deixe depois submerso.", cue: "Os tentáculos curvam. Se ficarem direitos, a água não estava a ferver." },
        { do: "Lume médio, 40–45 min para 1,2 kg (conte a partir de voltar a ferver). Prove um tentáculo aos 35 min: o dente deve entrar sem luta, como uma batata cozida.", cue: "Se ainda estiver borracha, +8 min. Se se desfizer, já passou: tire já." },
        { do: "Tire o polvo, deixe 5 min. Na mesma água, sal grosso e batata 15–18 min até o garfo entrar. Escorra.", cue: "Batata inteira, não papa." },
        { do: "Corte o polvo em rodelas de 1 cm (tentáculos) e a cabeça em tiras. Fonte: batata, polvo, sal grosso, pimentón, azeite a um fio. Sirva morno.", cue: "O azeite brilha. O pimentón não se queima — vai cru por cima, nunca frito neste prato." },
      ],
      tip: "Congelar 48 h e descongelar no frio substitui as porradas da avó.",
      mistakes: "Sal na água do polvo no início (endurece a pele). Pimentón na frigideira (amarga). Polvo de 3 kg com os mesmos 40 min (fica cru no centro).",
      serve: "Fonte no centro. Pão. 4 pessoas como entrada farta, 2 como prato.",
    },
    es: {
      name: "Pulpo a la gallega",
      origin: "Galicia. Pulpo, cachelos, pimentón y aceite. Congelado y el 'susto' en el agua.",
      honest: "Pulpo congelado y descongelado en nevera queda más tierno. Pimentón dulce de la Vera.",
      equipment: ["Olla ancha", "Tijeras", "Fuente"],
      ings: [
        ["1,2 kg", "pulpo, mejor congelado y descongelado 24 h"],
        ["800 g", "patata en gajos con piel"],
        ["8 g", "sal gorda"],
        ["8 g", "pimentón dulce"],
        ["80 ml", "aceite de oliva"],
        ["al gusto", "pimentón picante"],
      ],
      steps: [
        { do: "Agua hirviendo. Susto: 3 inmersiones de 3 s. Luego sumergido.", cue: "Los tentáculos se rizan." },
        { do: "40–45 min a fuego medio. Pruebe a los 35: el diente entra como en una patata.", cue: "Si está goma, +8 min." },
        { do: "Saque el pulpo 5 min. En la misma agua, sal y patata 15–18 min.", cue: "Patata entera." },
        { do: "Rodajas de 1 cm. Fuente: patata, pulpo, sal, pimentón, aceite. Tibio.", cue: "El pimentón va crudo encima, nunca frito." },
      ],
      tip: "Congelar 48 h sustituye los golpes de antaño.",
      mistakes: "Sal al inicio en el pulpo. Pimentón en sartén. Mismos minutos para 3 kg.",
      serve: "Fuente al centro. Entrante para 4.",
    },
  },
  tacos: {
    time: 40, prep: 15, cook: 25, serves: 4, difficulty: "facil",
    pt: {
      name: "Tacos de bistec",
      origin: "México — taco de carne na chapa, tortilha de milho, cebola, coentros e lima. Não é kit de taco doce com queijo cheddar.",
      honest: "Tortilha de milho (nixtamal) muda o prato. Se só houver trigo, diga que é adaptação. Carne: alcatra ou vazia em tiras finas.",
      equipment: ["Chapa ou frigideira de ferro", "Pano para as tortilhas"],
      ings: [
        ["500 g", "alcatra em tiras de 5 mm"],
        ["12", "tortilhas de milho pequenas (Ø 10–12 cm)"],
        ["120 g", "cebola branca em cubos pequenos"],
        ["30 g", "coentros picados"],
        ["2", "limas"],
        ["8 g", "sal"],
        ["4 g", "cominhos moídos"],
        ["20 ml", "óleo"],
        ["a gosto", "salsa verde ou vermelha, e 1 chile serrano em rodelas"],
      ],
      steps: [
        { do: "Carne à temperatura ambiente 15 min. Sal e cominhos. Chapa muito quente, óleo 10 s. Carne numa camada, 2 min sem mexer, 1 min a virar. Tire. Não faça 3 camadas na frigideira — faça duas fornadas.", cue: "Beiras tostadas, centro ainda suculento. Suco na tábua, não um charco cinzento." },
        { do: "A mesma chapa: tortilhas 20 s por lado até amolecer e ter pintas. Empilhe num pano.", cue: "Flexível. Se rachar, estava fria ou velha: um fio de água na chapa e tape 10 s." },
        { do: "Monte na hora: carne, cebola crua, coentros, lima. Chile à parte.", cue: "A tortilha quente + cebola crua. Queijo cheddar por cima deixa de ser este taco." },
      ],
      tip: "A lima vai no fim, não na carne crua (cozinha a superfície e seca).",
      mistakes: "Tortilha fria de pacote. Carne a vapor em pilha. Molho doce de frasco a tapar tudo.",
      serve: "3 tacos por pessoa. Comem-se com a mão, de pé ou à mesa.",
    },
    es: {
      name: "Tacos de bistec",
      origin: "México. Carne a la plancha, tortilla de maíz, cebolla, cilantro y lima.",
      honest: "Tortilla de maíz. Si solo hay trigo, dígalo. Carne: solomillo o tapa en tiras.",
      equipment: ["Plancha o sartén de hierro", "Paño"],
      ings: [
        ["500 g", "solomillo en tiras de 5 mm"],
        ["12", "tortillas de maíz pequeñas"],
        ["120 g", "cebolla en cubos"],
        ["30 g", "cilantro"],
        ["2", "limas"],
        ["8 g", "sal"],
        ["4 g", "comino"],
        ["20 ml", "aceite"],
        ["al gusto", "salsa y chile serrano"],
      ],
      steps: [
        { do: "Carne 15 min fuera. Sal y comino. Plancha fuerte. 2 min + 1 min. Dos tandas.", cue: "Bordes tostados, centro jugoso." },
        { do: "Tortillas 20 s por lado. Paño.", cue: "Flexibles, con pintas." },
        { do: "Carne, cebolla cruda, cilantro, lima. Al momento.", cue: "Sin cheddar en esta ficha." },
      ],
      tip: "La lima al final, no en la carne cruda.",
      mistakes: "Tortilla fría. Carne en pila. Salsa dulce de bote.",
      serve: "3 tacos por persona.",
    },
  },
  pasta: {
    time: 25, prep: 10, cook: 15, serves: 2, difficulty: "facil",
    pt: {
      name: "Spaghetti aglio e olio",
      origin: "Nápoles / sul de Itália. Alho, azeite, malagueta, salsa. Sem queijo a tapar — se pôr parmesão, é outra receita.",
      honest: "Dois pratos. A água da massa é ingrediente, não se deita toda fora.",
      equipment: ["Panela de massa", "Frigideira larga"],
      ings: [
        ["200 g", "spaghetti n.º 5"],
        ["20 g", "sal para a água (1% da água: 2 l → 20 g)"],
        ["4 dentes", "alho em fatias finas"],
        ["60 ml", "azeite"],
        ["1", "malagueta seca, em pedaços (sem muitas sementes se não quiser fogo)"],
        ["15 g", "salsa lisa picada"],
      ],
      steps: [
        { do: "2 l de água a ferver, 20 g de sal. Spaghetti. Tempo da caixa menos 1 min.", cue: "A água sabe a mar. A massa ainda tem um ponto branco no centro." },
        { do: "Enquanto isso, frigideira em lume baixo: azeite, alho e malagueta 4–5 min. O alho fica loiro, nunca açafrão-escuro. Se escurecer, deite fora e recomece — amarga o prato.", cue: "Alho cor de palha. Cheira, não pica a fumegar." },
        { do: "Passe a massa à frigideira com 80 ml da água de cozer. Lume médio, 1 min, a agitar. A água e o azeite viram um molho que pega no fio.", cue: "Não há poça de azeite nem água solta. Cada spaghetti brilha." },
        { do: "Salsa fora do lume. Prove o sal. Sirva já.", cue: "Quente, perfume de alho. Se estiver seco, mais 1 c. sopa de água de massa." },
      ],
      tip: "Não escorra a massa até ficar sem nada: reserve a água antes.",
      mistakes: "Alho queimado. Queijo a mais. Massa escorrida 5 min à espera na peneira.",
      serve: "Prato fundo quente. 2 pessoas.",
    },
    es: {
      name: "Spaghetti aglio e olio",
      origin: "Nápoles. Ajo, aceite, guindilla, perejil. Sin queso que tape.",
      honest: "Dos platos. El agua de la pasta es ingrediente.",
      equipment: ["Olla", "Sartén ancha"],
      ings: [
        ["200 g", "spaghetti n.º 5"],
        ["20 g", "sal para 2 l de agua"],
        ["4 dientes", "ajo en láminas"],
        ["60 ml", "aceite de oliva"],
        ["1", "guindilla seca"],
        ["15 g", "perejil liso"],
      ],
      steps: [
        { do: "2 l de agua, 20 g de sal. Pasta: tiempo de caja menos 1 min.", cue: "El agua sabe a mar. Punto blanco en el centro." },
        { do: "Aceite, ajo y guindilla 4–5 min a fuego bajo. Ajo rubio. Si se oscurece, empiece de nuevo.", cue: "Color paja, sin humo." },
        { do: "Pasta + 80 ml del agua. 1 min agitando.", cue: "Cada hebra brilla; no hay charco." },
        { do: "Perejil fuera del fuego. Ya.", cue: "Si está seco, 1 cda. más de agua." },
      ],
      tip: "Reserve agua antes de escurrir.",
      mistakes: "Ajo quemado. Queso de más. Pasta esperando en el colador.",
      serve: "Dos platos.",
    },
  },
  onigiri: {
    time: 40, prep: 15, cook: 25, serves: 4, difficulty: "facil",
    pt: {
      name: "Onigiri",
      origin: "Japão. Bola de arroz japonês com recheio, para a mão. Não é sushi de peixe cru — em casa, isto é o que se faz sem risco de sashimi.",
      honest: "Arroz japonês de grão curto (ou 'arroz para sushi'). Arroz long-grain solta-se e não pega. Recheio desta ficha: atum em lata com maionese, seguro e testável.",
      equipment: ["Panela com tampa ou rice cooker", "Tigela com água e sal"],
      ings: [
        ["300 g", "arroz japonês cru (dá ~660 g cozido)"],
        ["360 ml", "água para cozer (depois de lavar)"],
        ["1 lata", "atum em azeite (120 g escorrido)"],
        ["30 g", "maionese"],
        ["8 g", "sal (mãos + arroz)"],
        ["2 folhas", "nori, cortadas em 8 tiras"],
      ],
      steps: [
        { do: "Lave o arroz em água fria 4 vezes, até a água sair quase clara. Escorra 10 min. Coza com 360 ml: fervura, lume mínimo 12 min tampado, 10 min de descanso sem abrir.", cue: "Grão brilhante, pega-se. Se estiver papo, havia água a mais; se estiver duro no centro, +2 min de lume mínimo." },
        { do: "Atum escorrido + maionese. 8 porções de arroz (~80 g). Tigela com água, 2 g de sal. Mãos molhadas.", cue: "O arroz ainda está quente (não queima). Frio não pega." },
        { do: "Cova no arroz, 1 c. chá de atum, feche. Aperte em triângulo ou bola, firme mas sem esmagar o grão. Nori na hora de comer, senão amolece.", cue: "Aguenta na mão. Se esfarelar, o arroz estava frio ou era a variedade errada." },
      ],
      tip: "Leve no pano, nori à parte. Umeboshi no lugar do atum se achar.",
      mistakes: "Arroz agulha. Nori de véspera no arroz. Apertar como bola de neve até virar cola.",
      serve: "2 onigiri por pessoa. Lanche ou picnic.",
    },
    es: {
      name: "Onigiri",
      origin: "Japón. Bola de arroz japonés. No es sushi de pescado crudo.",
      honest: "Arroz de grano corto. Relleno: atún de lata con mayonesa, seguro en casa.",
      equipment: ["Olla con tapa", "Cuenco con agua y sal"],
      ings: [
        ["300 g", "arroz japonés crudo"],
        ["360 ml", "agua"],
        ["1 lata", "atún en aceite (120 g escurrido)"],
        ["30 g", "mayonesa"],
        ["8 g", "sal"],
        ["2 hojas", "nori"],
      ],
      steps: [
        { do: "Lave 4 veces. 10 min. Cueza 12 min mínimo + 10 min reposo.", cue: "Grano brillante que pega." },
        { do: "Atún + mayonesa. Manos húmedas con sal. Arroz caliente.", cue: "Frío no pega." },
        { do: "Relleno, cierre, triángulo. Nori al comer.", cue: "Aguanta en la mano." },
      ],
      tip: "Nori aparte hasta el momento.",
      mistakes: "Arroz largo. Nori de víspera. Apretar hasta cola.",
      serve: "2 por persona.",
    },
  },
  burger: {
    time: 30, prep: 10, cook: 20, serves: 2, difficulty: "facil",
    pt: {
      name: "Hambúrguer",
      origin: "Estados Unidos. Carne moída, pão, fogo alto. A gordura é o suco: 80/20 (magro/gordo).",
      honest: "Dois hambúrgueres de 180 g. Sem ovo nem pão na mistura — isso é almôndega. Sal só na hora do lume.",
      equipment: ["Frigideira de ferro ou grelha", "Espátula"],
      ings: [
        ["360 g", "carne moída (acinhas ou acém + 20% gordura)"],
        ["2", "pães de hambúrguer"],
        ["2 fatias", "queijo cheddar ou prato"],
        ["2 folhas", "alface"],
        ["4", "rodelas de tomate"],
        ["20 g", "cebola em anéis finos"],
        ["6 g", "sal"],
        ["pimenta", "a gosto"],
        ["10 g", "manteiga para o pão"],
      ],
      steps: [
        { do: "Divida em 2. Faça discos de 2 cm, um pouco mais largos que o pão (encolhem). Covinha no centro com o polegar. Frio 10 min.", cue: "O disco segura. Se rachar, a carne estava demasiado magra ou quente." },
        { do: "Frigideira a fumar. Sal e pimenta só na face que vai descer. 3 min sem mexer, sem esmagar. Vire. Sal na segunda face. 3 min. Queijo no último 1 min, tampa 20 s.", cue: "Crosta castanha. Centro a 55–60 °C se tiver sonda (médio). Sem sonda: o suco no prato é rosa, não vermelho vivo nem cinza." },
        { do: "Pão na manteiga 30 s. Descanse a carne 2 min. Monte: pão, alface, carne, tomate, cebola, pão.", cue: "O pão não esborracha. Se a carne secar, a próxima vez 30 s a menos e não esmague." },
      ],
      tip: "Esmagar com a espátula deita o suco embora. Uma viragem só.",
      mistakes: "Sal na mistura 1 h antes (o suco sai). Carne 5% gordura. Pão cru frio.",
      serve: "1 hambúrguer por pessoa. Guardanapo. Batata é extra, não obrigatória.",
    },
    es: {
      name: "Hamburguesa",
      origin: "Estados Unidos. Carne picada 80/20, pan, fuego alto. Sin huevo en la mezcla.",
      honest: "Dos hamburguesas de 180 g. Sal solo al fuego.",
      equipment: ["Sartén de hierro", "Espátula"],
      ings: [
        ["360 g", "carne picada con 20% de grasa"],
        ["2", "panes"],
        ["2 lonchas", "queso"],
        ["2 hojas", "lechuga"],
        ["4", "rodajas de tomate"],
        ["20 g", "cebolla"],
        ["6 g", "sal"],
        ["10 g", "mantequilla para el pan"],
      ],
      steps: [
        { do: "2 discos de 2 cm, hoyito en el centro. 10 min en frío.", cue: "El disco se sostiene." },
        { do: "Sartén humeante. Sal en la cara que baja. 3 min, voltee, 3 min. Queso 1 min.", cue: "Costra marrón. Jugo rosa, no gris." },
        { do: "Pan 30 s. Carne 2 min de reposo. Monte.", cue: "Si se seca, 30 s menos y no aplaste." },
      ],
      tip: "No aplastar. Un solo volteo.",
      mistakes: "Sal en la mezcla 1 h antes. Carne muy magra.",
      serve: "Una por persona.",
    },
  },
  curry: {
    time: 45, prep: 15, cook: 30, serves: 4, difficulty: "facil",
    pt: {
      name: "Chana masala (curry de grão)",
      origin: "Norte da Índia / Punjabi. Grão-de-bico em molho de tomate, cominhos e garam masala. Não é 'um curry' genérico de frasco.",
      honest: "Grão de lata escorrido serve (2 latas de 400 g). Especiarias em lume 20 s no óleo — se queimarem, amargam e recomeça.",
      equipment: ["Panela larga", "Tampa"],
      ings: [
        ["480 g", "grão-de-bico cozido, escorrido (2 latas)"],
        ["400 g", "tomate pelado triturado"],
        ["150 g", "cebola picada"],
        ["15 g", "gengibre fresco ralado"],
        ["3 dentes", "alho picado"],
        ["40 ml", "óleo"],
        ["6 g", "sal"],
        ["4 g", "cominhos em grão"],
        ["3 g", "cúrcuma"],
        ["4 g", "coentro em pó"],
        ["3 g", "garam masala"],
        ["1", "malagueta verde (opcional)"],
        ["20 g", "coentros frescos"],
        ["para servir", "250 g de arroz basmati cozido"],
      ],
      steps: [
        { do: "Óleo médio. Cominhos em grão 20 s até cheirar e um ou outro saltar. Cebola 8 min até loira. Gengibre, alho e malagueta 1 min.", cue: "Cebola doce, alho sem queimar." },
        { do: "Cúrcuma e coentro em pó 15 s. Tomate + sal. 10 min, mexer, até o óleo separar nas beiras.", cue: "O vermelho escurece e há um fio de óleo a circundar o molho." },
        { do: "Grão + 100 ml de água. Tampa, lume baixo, 12 min. Garam masala e coentros 1 min fora do lume forte.", cue: "O grão está quente por dentro e o molho pega na colher, não escorre como sopa." },
        { do: "Sirva com arroz basmati (ele só: lave, 1:1,5 arroz:água, 12 min tampado).", cue: "O arroz está solto. Se o curry estiver seco, 40 ml de água e 1 min." },
      ],
      tip: "Garam masala no fim, não no início com a cúrcuma — o perfume voa.",
      mistakes: "Especiarias 2 min no óleo (queimam). Grão 40 min a ferver (pele solta, papa). Frasco 'curry powder' a tapar tudo.",
      serve: "Tigela. Arroz ao lado, não por baixo a ensopar 10 min.",
    },
    es: {
      name: "Chana masala (curry de garbanzo)",
      origin: "Norte de India. Garbanzo en tomate, comino y garam masala. No es un bote genérico.",
      honest: "Vale garbanzo de lata. Especias 20 s en el aceite; si se queman, empiece de nuevo.",
      equipment: ["Olla ancha", "Tapa"],
      ings: [
        ["480 g", "garbanzos cocidos"],
        ["400 g", "tomate triturado"],
        ["150 g", "cebolla"],
        ["15 g", "jengibre fresco"],
        ["3 dientes", "ajo"],
        ["40 ml", "aceite"],
        ["6 g", "sal"],
        ["4 g", "comino en grano"],
        ["3 g", "cúrcuma"],
        ["4 g", "cilantro en polvo"],
        ["3 g", "garam masala"],
        ["20 g", "cilantro fresco"],
        ["para servir", "arroz basmati"],
      ],
      steps: [
        { do: "Comino 20 s. Cebolla 8 min. Jengibre y ajo 1 min.", cue: "Cebolla rubia, ajo sin quemar." },
        { do: "Cúrcuma y cilantro 15 s. Tomate y sal 10 min, hasta que el aceite separe.", cue: "Un hilo de aceite en el borde." },
        { do: "Garbanzo + 100 ml de agua. 12 min. Garam masala y cilantro al final.", cue: "La salsa se sostiene en la cuchara." },
        { do: "Arroz basmati aparte.", cue: "Si está seco, 40 ml de agua." },
      ],
      tip: "Garam masala al final.",
      mistakes: "Especias 2 min. Garbanzo 40 min. Curry en polvo de bote.",
      serve: "Cuenco. Arroz al lado.",
    },
  },
  ceviche: {
    time: 30, prep: 20, cook: 10, serves: 2, difficulty: "media",
    pt: {
      name: "Ceviche de peixe",
      origin: "Peru. Peixe cru 'cozido' no ácido da lima, cebola roxa, aji, milho. Comida de imediato.",
      honest: "Segurança: só peixe de confiança, muito fresco, mantido no frio. Se não tiver isso, não faça este prato — faça a muqueca ou os tacos. Crianças, grávidas e imunidade baixa: evite peixe cru.",
      equipment: ["Tigela de vidro ou inox (não alumínio)", "Faca afiada", "Frigorífico"],
      ings: [
        ["400 g", "peixe branco muito fresco (corvina, dourada, linguado), em cubos de 1,5 cm"],
        ["120 ml", "sumo de lima recém-espremido (cerca de 5–6 limas)"],
        ["80 g", "cebola roxa em pena bem fina"],
        ["1", "aji amarelo ou ½ malagueta sem sementes, picada"],
        ["6 g", "sal"],
        ["15 g", "coentros"],
        ["80 g", "milho cozido (choclo ou milho doce)"],
        ["para servir", "batata-doce cozida em cubos, se achar"],
      ],
      steps: [
        { do: "Peixe: cheiro a mar, carne firme, não pegajosa. Cubos iguais. Cebola 10 min em água fria, escorra — tira o ardor.", cue: "Se o peixe cheirar a amoníaco ou estiver mole, deite fora. Não 'aproveite'." },
        { do: "Tigela fria: peixe, sal, aji, lima a cobrir. 10 min no frio, não 1 h. Mexa 1 vez.", cue: "A superfície do cubo fica opaca; o centro ainda pode estar translúcido — é o ponto peruano. 30 min deixa borracha." },
        { do: "Cebola, coentros, milho. Prove o sal. Sirva já, bem frio. Não guarde para amanhã.", cue: "O prato está ácido, salgado, crocante de cebola. Se estiver mole e branco por completo, passou de tempo." },
      ],
      tip: "A lima vai espremida na hora. Lima de véspera no copo oxida e amarga.",
      mistakes: "Peixe de 3 dias. 2 h de lima (fica estopa). Alumínio (gosto metálico). Guardar de um dia para o outro.",
      serve: "Prato frio. 2 pessoas como prato, 4 como entrada. Coma em 15 min.",
    },
    es: {
      name: "Ceviche de pescado",
      origin: "Perú. Pescado en lima, cebolla morada, ají, maíz. Al momento.",
      honest: "Solo pescado de confianza, muy fresco, en frío. Si no lo tiene, no haga este plato. Niños, embarazo, inmunidad baja: evite pescado crudo.",
      equipment: ["Bol de vidrio o inox", "Cuchillo", "Nevera"],
      ings: [
        ["400 g", "pescado blanco muy fresco en cubos de 1,5 cm"],
        ["120 ml", "zumo de lima (5–6 limas)"],
        ["80 g", "cebolla morada en pluma"],
        ["1", "ají o ½ guindilla"],
        ["6 g", "sal"],
        ["15 g", "cilantro"],
        ["80 g", "maíz cocido"],
      ],
      steps: [
        { do: "Pescado firme, olor a mar. Cebolla 10 min en agua fría.", cue: "Si huele a amoníaco, tírelo." },
        { do: "Pescado, sal, ají, lima. 10 min en frío, no 1 h.", cue: "Superficie opaca, centro aún translúcido. 30 min lo pone goma." },
        { do: "Cebolla, cilantro, maíz. Ya. No para mañana.", cue: "Ácido, salado, crujiente." },
      ],
      tip: "Lima exprimida al momento.",
      mistakes: "Pescado de 3 días. 2 h en lima. Aluminio. Guardar.",
      serve: "Frío. 2 como plato, 4 como entrada. En 15 min.",
    },
  },
};
